version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.production
    command: ["make", "test"]
    environment:
      NODOS_DB_TYPE: sqljs
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 54321:5432
