version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.production
    command: ["npm", "test"]
    ports:
    - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USERNAME: ${NODOS_DB_USERNAME}
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD}
    ports:
      - 54321:5432
