name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker/compose:1.29.1

    steps:
      - uses: actions/checkout@1

      - name: Run Tests
        run: make compose-ci

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.production
          tags: feycot/devops-for-programmers-project-lvl1:latest
