name: ci

on: [push]

env:
  BUILDKIT_INLINE_CACHE: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Build
        run: make compose-ci-build

      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "feycot/devops-for-programmers-project-lvl1:latest"

      - uses: actions/upload-artifact@v2
        with:
          name: Dockerfile.production
          path: Dockerfile.production

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download image
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: "feycot/devops-for-programmers-project-lvl1:latest"

      - name: Run Tests
        run: docker run -it feycot/devops-for-programmers-project-lvl1:latest make test

  docker:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Dockerfile.production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.production
          tags: feycot/devops-for-programmers-project-lvl1:latest
