name: ci

on: [push]

env:
  BUILDKIT_INLINE_CACHE: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: make compose-ci

  proverochka:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - run: ls -la

  # docker:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Push to Docker Hub
  #       uses: docker/build-push-action@v2
  #       with:
  #         file: Dockerfile.production
  #         tags: feycot/devops-for-programmers-project-lvl1:latest
