name: ci

on: [push]

env:
  BUILDKIT_INLINE_CACHE: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  PRODUCTION_IMAGE_TAG: feycot/devops-for-programmers-project-lvl1:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Build
        run: make build

      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: ${{ env.PRODUCTION_IMAGE_TAG }}

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download image
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: ${{ env.PRODUCTION_IMAGE_TAG }}

      - name: Run Tests
        run: docker run ${{ env.PRODUCTION_IMAGE_TAG }} make test

  docker:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.production
          tags: ${{ env.PRODUCTION_IMAGE_TAG }}
